theme: jekyll-theme-minimal
title: CS 3510 Fall 2021
description: This is the course page for Georgia Tech's CS 3510, *Algorithms* 
logo: https://gtalgorithms.files.wordpress.com/2018/01/cropped-vc31.jpg?w=240

 
