theme: jekyll-theme-minimal
title: GT CS 3510 - Fall 2020
description: This is the course page for Georgia Tech's CS 3510, *Algorithms* 
logo: https://www.stephotec.com/wp-content/uploads/2018/12/algorithm-2.png

 
